### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mobilekosmos** [drewhamilton/AndroidDateTimeFormatters#35]
Is this not yet integrated into Android itself?
And does using this lib maintain the usage of the localized "at" before the time?

I'm currently using this one:

```
fun parseAndFormatDateTime(dateString: String, context: Context): String? {
    return try {
        val instant = Instant.parse(dateString)
        val localDateTime = instant.atZone(ZoneId.systemDefault()).toLocalDateTime()

        val is24HourFormat: Boolean = android.text.format.DateFormat.is24HourFormat(context)
        val timePattern = if (is24HourFormat) "H:mm" else "h:mm a"

        val formatter = DateTimeFormatterBuilder()
            .appendLocalized(FormatStyle.FULL, null)
            .appendLiteral(", ")
            .appendPattern(timePattern)
            .toFormatter(Locale.getDefault())

        // This version has the advantage of using "at hh:mm", but is not aware of Android System Settings. If the user
        //  forces 12/24 in the system settings this would not be considered.
        // val formatter = DateTimeFormatter
        //     .ofLocalizedDateTime(FormatStyle.FULL, FormatStyle.SHORT)
        //     .withLocale(Locale.getDefault())

        formatter.format(localDateTime)
    } catch (e: Exception) {
        null
    }
}
```

**Comment by drewhamilton** [comment]
> Is this not yet integrated into Android itself?

Not as far as I know, though I haven't checked in quite awhile.

Different locales have different punctuation and spacing conventions, so while your pasted solution might work fine for some locales, it might look strange for users in other locales. This library will find the appropriate format for the given locale, and then substitute the appropriate 12/24 setting afterward.

**Comment by mobilekosmos** [comment]
"Different locales have different punctuation and spacing conventions" Any example from the top of your head? DateTimeFormatter already takes care of localization, I though your lib is only for handling the missing part of taking into accout the Android Time System Setting?

**Comment by drewhamilton** [comment]
`DateTimeFormatter` always localizes words in the formatted output: "April"/"aprile"/"апреля". And it takes care of using a localized pattern if that pattern is fetched via `ofLocalized...`, like the date portion of your example: "Saturday, April 24, 2010" / "sabato 24 aprile 2010".

But the time portion in your example is one of two hard-coded patterns (depending on 12/24 setting), always using `:`. According to [Wikipedia](https://en.wikipedia.org/wiki/Date_and_time_notation_in_France), France typically uses an `h` instead of a `:`, as in `14h05`. If Android includes that `h` for the France locale, then this library will too.

**Comment by drewhamilton** [comment]
If there's a locale that includes "at" literal text, this lib should support that too. I'm not sure which locale includes that but I'd definitely accept a test verifying this behavior!

**Comment by drewhamilton** [comment]
Added a test in #74 demonstrating that Android uses `h` instead of `:` on API 28+ for the Canada (French) locale, and it's preserved when switching the 12/24 setting.
